---
version: "3.6"

services:

  portainer:
    image: portainer/portainer
    restart: always
    command: -H unix:///var/run/docker.sock
    ports:
      - "${PORT_PORTAINER}:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer/data:/data
      - /etc/localtime:/etc/localtime:ro

  organizr:
    image: organizrtools/organizr-v2:plex
    restart: always
    environment:
      - PUID
      - PGID
    ports:
      - "${PORT_ORGANIZR}:80"
    volumes:
      - ./organizr:/config

  watchtower:
    image: v2tec/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 0 4 * * *" --cleanup

  homeassistant:
    image: homeassistant/home-assistant
    restart: always
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/ttyUSB1:/dev/ttyUSB1
      - /dev/ttyACM0:/dev/ttyACM0
    environment:
      - PUID
      - PGID
      - TZ
    ports:
      - "${PORT_HOMEASSISTANT}:8123"
    privileged: true
    volumes:
      - ./homeassistant:/config
      - /etc/localtime:/etc/localtime:ro

  plexms:
    restart: always
    image: plexinc/pms-docker
    environment:
      - TZ
      - HOSTNAME="Docker Plex"
      - PLEX_CLAIM
      - PLEX_UID=${PUID}
      - PLEX_GID=${PGID}
    network_mode: host
    volumes:
      - ./plexms:/config
      - ./Plex_tmp:/transcode
      - ${PLEX_SHARE}:/data
      - /etc/localtime:/etc/localtime:ro

  tautulli:
    image: linuxserver/tautulli
    restart: always
    environment:
      - PUID
      - PGID
      - TZ
    ports:
      - "${PORT_TAUTULLI}:8181"
    volumes:
      - ./tautulli/config:/config
      - ./tautulli/logs:/logs:ro
      - /etc/localtime:/etc/localtime:ro

  glances:
    image: vimagick/glances
    restart: always
    environment:
      - GLANCES_OPT=-w
      - TZ
    network_mode: host
    pid: host
    volumes:
      - ./glances:/etc/glances
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/localtime:/etc/localtime:ro

  db:
    image: postgres:11.1-alpine
    restart: always
    environment:
      - POSTGRES_DB
      - POSTGRES_PASSWORD
      - POSTGRES_USER
    user: ${PUID}:${PGID}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - /etc/passwd:/etc/passwd:ro

  adminer:
    image: adminer:4.7
    restart: always
    depends_on:
      - db
    ports:
      - "${PORT_ADMINER}:8080"

  nextcloud:
    image: nextcloud
    restart: always
    depends_on:
      - db
    environment:
      - NEXTCLOUD_ADMIN_USER
      - NEXTCLOUD_ADMIN_PASSWORD
      - POSTGRES_DB=nextcloud
      - POSTGRES_PASSWORD
      - POSTGRES_USER
      - POSTGRES_HOST=db
    ports:
      - "${PORT_NEXTCLOUD}:80"
    volumes:
      - ./nextcloud/html:/var/www/html
