// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/apis/widgets/widgets.proto

package widgetsapi

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Supported sort orders
type ListRequest_OrderBy int32

const (
	ListRequest_DEFAULT ListRequest_OrderBy = 0
	ListRequest_NAME    ListRequest_OrderBy = 1
)

// Enum value maps for ListRequest_OrderBy.
var (
	ListRequest_OrderBy_name = map[int32]string{
		0: "DEFAULT",
		1: "NAME",
	}
	ListRequest_OrderBy_value = map[string]int32{
		"DEFAULT": 0,
		"NAME":    1,
	}
)

func (x ListRequest_OrderBy) Enum() *ListRequest_OrderBy {
	p := new(ListRequest_OrderBy)
	*p = x
	return p
}

func (x ListRequest_OrderBy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListRequest_OrderBy) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_apis_widgets_widgets_proto_enumTypes[0].Descriptor()
}

func (ListRequest_OrderBy) Type() protoreflect.EnumType {
	return &file_pkg_apis_widgets_widgets_proto_enumTypes[0]
}

func (x ListRequest_OrderBy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListRequest_OrderBy.Descriptor instead.
func (ListRequest_OrderBy) EnumDescriptor() ([]byte, []int) {
	return file_pkg_apis_widgets_widgets_proto_rawDescGZIP(), []int{3, 0}
}

type Widget struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// generated uuid
	Uuid string `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	// user friendly name
	Name          string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Widget) Reset() {
	*x = Widget{}
	mi := &file_pkg_apis_widgets_widgets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Widget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Widget) ProtoMessage() {}

func (x *Widget) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_widgets_widgets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Widget.ProtoReflect.Descriptor instead.
func (*Widget) Descriptor() ([]byte, []int) {
	return file_pkg_apis_widgets_widgets_proto_rawDescGZIP(), []int{0}
}

func (x *Widget) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Widget) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// user friendly name
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_pkg_apis_widgets_widgets_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_widgets_widgets_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_widgets_widgets_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FindRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FindRequest) Reset() {
	*x = FindRequest{}
	mi := &file_pkg_apis_widgets_widgets_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FindRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FindRequest) ProtoMessage() {}

func (x *FindRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_widgets_widgets_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FindRequest.ProtoReflect.Descriptor instead.
func (*FindRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_widgets_widgets_proto_rawDescGZIP(), []int{2}
}

func (x *FindRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type ListRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Specify the sort order for the results.
	OrderBy ListRequest_OrderBy `protobuf:"varint,1,opt,name=order_by,json=orderBy,proto3,enum=widgetsapi.ListRequest_OrderBy" json:"order_by,omitempty"`
	// Maximum entries per page
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	// The next_page_token returned from a previous list request if any.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// Further fields are bound to query parameters and act to filter the result
	Name          string `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_pkg_apis_widgets_widgets_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_widgets_widgets_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_widgets_widgets_proto_rawDescGZIP(), []int{3}
}

func (x *ListRequest) GetOrderBy() ListRequest_OrderBy {
	if x != nil {
		return x.OrderBy
	}
	return ListRequest_DEFAULT
}

func (x *ListRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *ListRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *ListRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ListResponse struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Widgets []*Widget              `protobuf:"bytes,1,rep,name=widgets,proto3" json:"widgets,omitempty"`
	// Token to retrieve the next page of results or empty if there are none.
	NextPageToken string `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_pkg_apis_widgets_widgets_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_widgets_widgets_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_widgets_widgets_proto_rawDescGZIP(), []int{4}
}

func (x *ListResponse) GetWidgets() []*Widget {
	if x != nil {
		return x.Widgets
	}
	return nil
}

func (x *ListResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type UpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Unique identity of widget.
	Uuid   string  `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	Widget *Widget `protobuf:"bytes,2,opt,name=widget,proto3" json:"widget,omitempty"`
	// The mask says exactly which fields are to be updated. This
	// removes the ambiguity caused by 'zero' valued fields.
	Mask          *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_pkg_apis_widgets_widgets_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_widgets_widgets_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_widgets_widgets_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *UpdateRequest) GetWidget() *Widget {
	if x != nil {
		return x.Widget
	}
	return nil
}

func (x *UpdateRequest) GetMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.Mask
	}
	return nil
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_pkg_apis_widgets_widgets_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_widgets_widgets_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_widgets_widgets_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteRequest) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

var File_pkg_apis_widgets_widgets_proto protoreflect.FileDescriptor

const file_pkg_apis_widgets_widgets_proto_rawDesc = "" +
	"\n" +
	"\x1epkg/apis/widgets/widgets.proto\x12\n" +
	"widgetsapi\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\"0\n" +
	"\x06Widget\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"#\n" +
	"\rCreateRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"!\n" +
	"\vFindRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\"\xbb\x01\n" +
	"\vListRequest\x12:\n" +
	"\border_by\x18\x01 \x01(\x0e2\x1f.widgetsapi.ListRequest.OrderByR\aorderBy\x12\x1b\n" +
	"\tpage_size\x18\x02 \x01(\x05R\bpageSize\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\" \n" +
	"\aOrderBy\x12\v\n" +
	"\aDEFAULT\x10\x00\x12\b\n" +
	"\x04NAME\x10\x01\"d\n" +
	"\fListResponse\x12,\n" +
	"\awidgets\x18\x01 \x03(\v2\x12.widgetsapi.WidgetR\awidgets\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\x7f\n" +
	"\rUpdateRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12*\n" +
	"\x06widget\x18\x02 \x01(\v2\x12.widgetsapi.WidgetR\x06widget\x12.\n" +
	"\x04mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskR\x04mask\"#\n" +
	"\rDeleteRequest\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid2\xb6\x02\n" +
	"\aWidgets\x129\n" +
	"\x06Create\x12\x19.widgetsapi.CreateRequest\x1a\x12.widgetsapi.Widget\"\x00\x129\n" +
	"\bFindByID\x12\x17.widgetsapi.FindRequest\x1a\x12.widgetsapi.Widget\"\x00\x12;\n" +
	"\x04List\x12\x17.widgetsapi.ListRequest\x1a\x18.widgetsapi.ListResponse\"\x00\x129\n" +
	"\x06Update\x12\x19.widgetsapi.UpdateRequest\x1a\x12.widgetsapi.Widget\"\x00\x12=\n" +
	"\x06Delete\x12\x19.widgetsapi.DeleteRequest\x1a\x16.google.protobuf.Empty\"\x00B5Z3github.com/eccles/hestia/pkg/api/widgets;widgetsapib\x06proto3"

var (
	file_pkg_apis_widgets_widgets_proto_rawDescOnce sync.Once
	file_pkg_apis_widgets_widgets_proto_rawDescData []byte
)

func file_pkg_apis_widgets_widgets_proto_rawDescGZIP() []byte {
	file_pkg_apis_widgets_widgets_proto_rawDescOnce.Do(func() {
		file_pkg_apis_widgets_widgets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_apis_widgets_widgets_proto_rawDesc), len(file_pkg_apis_widgets_widgets_proto_rawDesc)))
	})
	return file_pkg_apis_widgets_widgets_proto_rawDescData
}

var file_pkg_apis_widgets_widgets_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_apis_widgets_widgets_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_pkg_apis_widgets_widgets_proto_goTypes = []any{
	(ListRequest_OrderBy)(0),      // 0: widgetsapi.ListRequest.OrderBy
	(*Widget)(nil),                // 1: widgetsapi.Widget
	(*CreateRequest)(nil),         // 2: widgetsapi.CreateRequest
	(*FindRequest)(nil),           // 3: widgetsapi.FindRequest
	(*ListRequest)(nil),           // 4: widgetsapi.ListRequest
	(*ListResponse)(nil),          // 5: widgetsapi.ListResponse
	(*UpdateRequest)(nil),         // 6: widgetsapi.UpdateRequest
	(*DeleteRequest)(nil),         // 7: widgetsapi.DeleteRequest
	(*fieldmaskpb.FieldMask)(nil), // 8: google.protobuf.FieldMask
	(*emptypb.Empty)(nil),         // 9: google.protobuf.Empty
}
var file_pkg_apis_widgets_widgets_proto_depIdxs = []int32{
	0, // 0: widgetsapi.ListRequest.order_by:type_name -> widgetsapi.ListRequest.OrderBy
	1, // 1: widgetsapi.ListResponse.widgets:type_name -> widgetsapi.Widget
	1, // 2: widgetsapi.UpdateRequest.widget:type_name -> widgetsapi.Widget
	8, // 3: widgetsapi.UpdateRequest.mask:type_name -> google.protobuf.FieldMask
	2, // 4: widgetsapi.Widgets.Create:input_type -> widgetsapi.CreateRequest
	3, // 5: widgetsapi.Widgets.FindByID:input_type -> widgetsapi.FindRequest
	4, // 6: widgetsapi.Widgets.List:input_type -> widgetsapi.ListRequest
	6, // 7: widgetsapi.Widgets.Update:input_type -> widgetsapi.UpdateRequest
	7, // 8: widgetsapi.Widgets.Delete:input_type -> widgetsapi.DeleteRequest
	1, // 9: widgetsapi.Widgets.Create:output_type -> widgetsapi.Widget
	1, // 10: widgetsapi.Widgets.FindByID:output_type -> widgetsapi.Widget
	5, // 11: widgetsapi.Widgets.List:output_type -> widgetsapi.ListResponse
	1, // 12: widgetsapi.Widgets.Update:output_type -> widgetsapi.Widget
	9, // 13: widgetsapi.Widgets.Delete:output_type -> google.protobuf.Empty
	9, // [9:14] is the sub-list for method output_type
	4, // [4:9] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_pkg_apis_widgets_widgets_proto_init() }
func file_pkg_apis_widgets_widgets_proto_init() {
	if File_pkg_apis_widgets_widgets_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_apis_widgets_widgets_proto_rawDesc), len(file_pkg_apis_widgets_widgets_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_apis_widgets_widgets_proto_goTypes,
		DependencyIndexes: file_pkg_apis_widgets_widgets_proto_depIdxs,
		EnumInfos:         file_pkg_apis_widgets_widgets_proto_enumTypes,
		MessageInfos:      file_pkg_apis_widgets_widgets_proto_msgTypes,
	}.Build()
	File_pkg_apis_widgets_widgets_proto = out.File
	file_pkg_apis_widgets_widgets_proto_goTypes = nil
	file_pkg_apis_widgets_widgets_proto_depIdxs = nil
}
