// Code generated by ../../../scripts/grpcserver.sh. DO NOT EDIT.
package widgets

import (
	"fmt"

	"github.com/eccles/hestia/pkg/apis/widgets"
	"github.com/eccles/hestia/pkg/connections"
	"github.com/eccles/hestia/pkg/logger"
)

type loggerContextKey string

type Service struct {
	widgetsAPI.UnimplementedWidgetsServer

	LogLevel string
	logger   logger.Logger

	GRPCServerPort string

	connections.Connections
}

func (s *Service) Run() error {

	s.logger = logger.New(s.LogLevel)

	if s.GRPCServerPort != "" {
		grpcServer, err := s.StartGRPCServer()
		if err != nil {
			return fmt.Errorf("start failure: %w", err)
		}
		defer grpcServer.GracefulStop()
	}

	return s.Connect(&s.logger)
}
