// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.1
// source: pkg/services/widgets/widgets.proto

package widgets

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WidgetsClient is the client API for Widgets service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WidgetsClient interface {
	//
	// create a widget
	Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Widget, error)
	//
	// returns specific widget
	FindByID(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*Widget, error)
	//
	// returns list of all widgets
	List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error)
	//
	// update a widget
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Widget, error)
	//
	// delete a widget
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type widgetsClient struct {
	cc grpc.ClientConnInterface
}

func NewWidgetsClient(cc grpc.ClientConnInterface) WidgetsClient {
	return &widgetsClient{cc}
}

func (c *widgetsClient) Create(ctx context.Context, in *CreateRequest, opts ...grpc.CallOption) (*Widget, error) {
	out := new(Widget)
	err := c.cc.Invoke(ctx, "/widgets.Widgets/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetsClient) FindByID(ctx context.Context, in *FindRequest, opts ...grpc.CallOption) (*Widget, error) {
	out := new(Widget)
	err := c.cc.Invoke(ctx, "/widgets.Widgets/FindByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetsClient) List(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*ListResponse, error) {
	out := new(ListResponse)
	err := c.cc.Invoke(ctx, "/widgets.Widgets/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetsClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*Widget, error) {
	out := new(Widget)
	err := c.cc.Invoke(ctx, "/widgets.Widgets/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *widgetsClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/widgets.Widgets/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WidgetsServer is the server API for Widgets service.
// All implementations must embed UnimplementedWidgetsServer
// for forward compatibility
type WidgetsServer interface {
	//
	// create a widget
	Create(context.Context, *CreateRequest) (*Widget, error)
	//
	// returns specific widget
	FindByID(context.Context, *FindRequest) (*Widget, error)
	//
	// returns list of all widgets
	List(context.Context, *ListRequest) (*ListResponse, error)
	//
	// update a widget
	Update(context.Context, *UpdateRequest) (*Widget, error)
	//
	// delete a widget
	Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedWidgetsServer()
}

// UnimplementedWidgetsServer must be embedded to have forward compatible implementations.
type UnimplementedWidgetsServer struct {
}

func (UnimplementedWidgetsServer) Create(context.Context, *CreateRequest) (*Widget, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedWidgetsServer) FindByID(context.Context, *FindRequest) (*Widget, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindByID not implemented")
}
func (UnimplementedWidgetsServer) List(context.Context, *ListRequest) (*ListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedWidgetsServer) Update(context.Context, *UpdateRequest) (*Widget, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedWidgetsServer) Delete(context.Context, *DeleteRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedWidgetsServer) mustEmbedUnimplementedWidgetsServer() {}

// UnsafeWidgetsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WidgetsServer will
// result in compilation errors.
type UnsafeWidgetsServer interface {
	mustEmbedUnimplementedWidgetsServer()
}

func RegisterWidgetsServer(s grpc.ServiceRegistrar, srv WidgetsServer) {
	s.RegisterService(&Widgets_ServiceDesc, srv)
}

func _Widgets_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/widgets.Widgets/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetsServer).Create(ctx, req.(*CreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Widgets_FindByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetsServer).FindByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/widgets.Widgets/FindByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetsServer).FindByID(ctx, req.(*FindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Widgets_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/widgets.Widgets/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetsServer).List(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Widgets_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/widgets.Widgets/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetsServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Widgets_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WidgetsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/widgets.Widgets/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WidgetsServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Widgets_ServiceDesc is the grpc.ServiceDesc for Widgets service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Widgets_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "widgets.Widgets",
	HandlerType: (*WidgetsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Widgets_Create_Handler,
		},
		{
			MethodName: "FindByID",
			Handler:    _Widgets_FindByID_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Widgets_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Widgets_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Widgets_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/services/widgets/widgets.proto",
}
