// Code generated by mockery v2.10.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// UnsafeWidgetsServer is an autogenerated mock type for the UnsafeWidgetsServer type
type UnsafeWidgetsServer struct {
	mock.Mock
}

// mustEmbedUnimplementedWidgetsServer provides a mock function with given fields:
func (_m *UnsafeWidgetsServer) mustEmbedUnimplementedWidgetsServer() {
	_m.Called()
}
