
[[language]]
name = "python"
roots = ["pyproject.toml"]
formatter = { command = "black", args = ["--quiet", "-"] }
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config = {} 
auto-format = true

[[language]] 
name = "go"
auto-format = true

