name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write # to fetch code (actions/checkout)

jobs:
  vulncheck:
    name: Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup ASDF VM
        # TODO: use @v4 when released https://github.com/asdf-vm/actions/issues/594
        uses: asdf-vm/actions/install@9cd779f40fe38688dd19505ccbc4eaaf018b44e7
        with:
          asdf_version: 0.16.7
      - name: tools 
        run: just tools
        shell: bash
      - name: generate 
        run: just generate
        shell: bash
      - name: qa
        run: just qa
        shell: bash
      - name: unittests
        run: just unittests
        shell: bash
      - name: build
        run: just build
        shell: bash
