name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  vulncheck:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup ASDF VM
        # TODO: use @v4 when released https://github.com/asdf-vm/actions/issues/594
        uses: asdf-vm/actions/install@1902764435ca0dd2f3388eea723a4f92a4eb8302
        with:
          asdf_version: 0.16.7
      - name: tools 
        run: just tools
        shell: bash
      - name: generate 
        run: just generate
        shell: bash
      - name: qa
        run: just qa
        shell: bash
      - name: unittests
        run: just unittest
        shell: bash
      - name: build
        run: just build
        shell: bash
