name: ci
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  QA:
    name: Quality Assurance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup ASDF VM
        uses: asdf-vm/actions/install@v4
      - name: tools 
        run: just tools
        shell: bash
      - name: generate 
        run: just generate
        shell: bash
      - name: qa
        run: just qa
        shell: bash
      - name: Check if there are any uncommitted changes
        run: just check
        shell: bash
      - name: unittests
        run: just unittest
        shell: bash
      - name: build
        run: just build
        shell: bash
